#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: galasactl-build
  namespace: galasa-tekton
spec:
  resources:
  - name: git-cli
    type: git
  - name: git-framework
    type: git
  params:
  - name: distBranch
    type: string
  - name: noPush
    type: string
    default: ""
  workspaces:
  - name: clibin
    optional: true
  tasks:
  - name: galasactl
    taskRef:
      name: galasactl-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: noPush
      value: $(params.noPush)
    resources:
      inputs:
      - name: git-cli
        resource: git-cli
      - name: git-framework
        resource: git-framework
    workspaces:
     - name: clibin
       workspace: clibin
  - name: release-galasactl
    taskRef:
      name: galasactl-release
    runAfter:
    - galasactl
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: noPush
      value: $(params.noPush)
    resources:
      inputs:
      - name: git-cli
        resource: git-cli
    workspaces:
     - name: clibin
       workspace: clibin
