#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: galasactl-release
  namespace: galasa-tekton
spec:
  resources:
    inputs:
    - name: git-cli
      type: git
  workspaces:
  - name: clibin
    optional: true
    mountpath: /workspace/git-cli/bin
  params:
  - name: noPush
    type: string
    default: ""
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  steps:
  - name: create-release
    workingDir: /workspace/git-cli
    image: $(params.dockerRepo)/galasa/galasa-build
    script: |
      #!/bin/sh
      set +e
      VERSION="$(cat VERSION)"
      echo version is $VERSION
      gh auth login --with-token < /root/githubcli/token
      git push origin :refs/tags/v$VERSION
      gh release delete v$VERSION      
      gh release create v$VERSION --prerelease --notes "Prerelease" --title "$VERSION" --repo galasa-dev/cli bin/galasactl*      
    volumeMounts:
      - name: githubsecret
        mountPath: /root/githubcli
  volumes:
    - name: githubsecret
      secret:
        secretName: github-creds
        items:
        - key: password
          path: token
