#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: binary-cli
spec:
  type: ClusterIP
  selector:
    app: binary-cli
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
