#
# Copyright contributors to the Galasa project.go
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cli-main-repo
  namespace: argocd
spec:
  project: galasa
  source:
    repoURL: 'https://github.com/galasa-dev/cli.git'
    path: argocd/repositoryHelm
    targetRevision: HEAD
    helm:
      parameters:
      - name: branch
        value: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: galasa-branch-main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
